# Generated by Django 5.1.4 on 2025-06-16 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={},
        ),
        migrations.AlterModelTable(
            name='login',
            table='Login',
        ),
        migrations.AlterModelTable(
            name='movie_posters',
            table='Movie Posters',
        ),
        migrations.AlterModelTable(
            name='register',
            table='Register',
        ),
    ]
