# Generated by Django 5.1.4 on 2025-06-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pata', '0002_alter_register_options_alter_login_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_posters',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='movie_posters',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie_posters',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movie_posters',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movie_posters',
            name='posters',
        ),
        migrations.RemoveField(
            model_name='movie_posters',
            name='year',
        ),
        migrations.AddField(
            model_name='movie_posters',
            name='cast',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie_posters',
            name='director',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie_posters',
            name='genres',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie_posters',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie_posters',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie_posters',
            name='release_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie_posters',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie_posters',
            name='streaming_on',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie_posters',
            name='writer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie_posters',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
