# Generated by Django 5.1.4 on 2025-06-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pata', '0003_remove_movie_posters_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie_posters',
            table='MoviePosters',
        ),
    ]
