# Generated by Django 5.1.4 on 2025-06-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pata', '0004_alter_movie_posters_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_posters',
            name='cast',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
