# Generated by Django 5.1.4 on 2025-06-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pata', '0009_alter_movie_posters_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_posters',
            name='cast',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
