# Generated by Django 5.1.4 on 2025-06-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pata', '0011_cast_remove_movie_posters_cast_movie_posters_cast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_posters',
            name='cast',
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
    ]
