# Generated by Django 5.1.4 on 2025-06-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pata', '0012_remove_movie_posters_cast_delete_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=100)),
                ('character_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cast_images/')),
            ],
        ),
        migrations.AddField(
            model_name='movie_posters',
            name='cast',
            field=models.ManyToManyField(related_name='movies', to='pata.cast'),
        ),
    ]
