# Generated by Django 5.1.4 on 2025-06-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pata', '0013_cast_movie_posters_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
