# Generated by Django 5.1.4 on 2025-07-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pata', '0014_alter_register_is_active_alter_register_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='register',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='register',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(default='NULL', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
