# Generated by Django 5.2.7 on 2025-10-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pata', '0015_alter_register_managers_remove_register_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='character_name',
        ),
    ]
